"""
FAISS vector-store loader.

The pre-built index is expected at ``data/faiss_index/`` (generated by
``ingest_data.py``).  The store is loaded once on application startup and
kept in module-level state so every request re-uses the same object.
"""

from typing import Optional
import os

from langchain_community.vectorstores import FAISS
from langchain_huggingface import HuggingFaceEndpointEmbeddings

from app.utils.config import FAISS_INDEX_PATH, HF_EMBEDDING_MODEL, HUGGINGFACEHUB_API_TOKEN
from app.utils.logger import logger

# Module-level singleton — populated by ``load_vector_store()``.
_vector_store: Optional[FAISS] = None


def load_vector_store() -> Optional[FAISS]:
    """Load (or reload) the FAISS index from disk and cache it."""
    global _vector_store

    # Check if index directory exists
    if not os.path.exists(FAISS_INDEX_PATH):
        logger.warning("FAISS index directory '%s' does not exist. Run ingest_data.py first.", FAISS_INDEX_PATH)
        return None

    # Check for required FAISS files
    index_file = os.path.join(FAISS_INDEX_PATH, "index.faiss")
    pkl_file = os.path.join(FAISS_INDEX_PATH, "index.pkl")
    if not os.path.exists(index_file) or not os.path.exists(pkl_file):
        logger.warning("FAISS index files not found in '%s'. Run ingest_data.py first.", FAISS_INDEX_PATH)
        return None

    logger.info("Loading FAISS index from '%s' …", FAISS_INDEX_PATH)
    try:
        embeddings = HuggingFaceEndpointEmbeddings(
            model=HF_EMBEDDING_MODEL,
            huggingfacehub_api_token=HUGGINGFACEHUB_API_TOKEN,
        )
        _vector_store = FAISS.load_local(
            FAISS_INDEX_PATH,
            embeddings,
            allow_dangerous_deserialization=True,
        )
        logger.info("FAISS index loaded successfully (%d vectors).", _vector_store.index.ntotal)
        return _vector_store
    except Exception as exc:
        logger.error("Failed to load FAISS index: %s", exc, exc_info=True)
        return None


def get_vector_store() -> Optional[FAISS]:
    """Return the cached vector-store instance (may be ``None`` if not loaded)."""
    return _vector_store
